spring:
  datasource:
    url: jdbc:mysql://149.129.78.187:3306/miaosha?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: 654321
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  rabbitmq:
    host: 149.129.78.187
    port: 5672
    username: root
    password: 654321
  thymeleaf:
    #prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    static-locations: classpath:/static/

redis:
  host: 149.129.78.187
  port: 6379
  timeout: 500
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500